using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Identity;
using SimbaFlow.Application.Common.Interfaces;
using SimbaFlow.Application.Common.Models;
using SimbaFlow.Domain.Entities.Identity;

namespace SimbaFlow.API.Features.Auth.Commands;

/// <summary>
/// Confirms MFA enrollment: the user proves possession of the authenticator by
/// submitting a valid TOTP code for the key generated by /mfa/setup. On success,
/// TwoFactorEnabled is turned on so subsequent logins require the second factor.
/// </summary>
public record EnableMfaCommand(string Code) : IRequest<Result>;

public class EnableMfaValidator : AbstractValidator<EnableMfaCommand>
{
    public EnableMfaValidator()
    {
        RuleFor(x => x.Code).NotEmpty().Length(6);
    }
}

public class EnableMfaHandler : IRequestHandler<EnableMfaCommand, Result>
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly ICurrentUserService _currentUser;

    public EnableMfaHandler(UserManager<ApplicationUser> userManager, ICurrentUserService currentUser)
    {
        _userManager = userManager;
        _currentUser = currentUser;
    }

    public async Task<Result> Handle(EnableMfaCommand request, CancellationToken cancellationToken)
    {
        if (string.IsNullOrEmpty(_currentUser.UserId))
            return Result.Failure("Not authenticated", 401);

        var user = await _userManager.FindByIdAsync(_currentUser.UserId);
        if (user is null)
            return Result.Failure("User not found", 404);

        var isValid = await _userManager.VerifyTwoFactorTokenAsync(
            user, _userManager.Options.Tokens.AuthenticatorTokenProvider, request.Code);
        if (!isValid)
            return Result.Failure("Invalid verification code", 401);

        if (!user.TwoFactorEnabled)
        {
            var setResult = await _userManager.SetTwoFactorEnabledAsync(user, true);
            if (!setResult.Succeeded)
                return Result.Failure(string.Join("; ", setResult.Errors.Select(e => e.Description)), 400);
        }

        return Result.Success();
    }
}
