export interface Candidate {
  id: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  localFullName?: string;
  passportNumber: string;
  labourId?: string;
  biometricId?: string;
  nationalId?: string;
  dateOfBirth: string;
  placeOfBirth?: string;
  gender: number;
  nationality?: string;
  religion?: string;
  maritalStatus?: string;
  numberOfChildren?: number;
  height?: string;
  weight?: string;
  passportType?: string;
  passportPlaceOfIssue?: string;
  passportIssueDate?: string;
  passportExpiryDate?: string;
  phoneNumber?: string;
  email?: string;
  address?: string;
  city?: string;
  country?: string;
  region?: string;
  subcity?: string;
  woreda?: string;
  houseNo?: string;
  occupation?: string;
  qualification?: string;
  monthlySalary?: string;
  contractPeriod?: string;
  englishLevel?: string;
  arabicLevel?: string;
  otherLanguages?: string;
  experienceAbroadYears?: number;
  worksIn?: string;
  referenceNo?: string;
  remark?: string;
  cookingLevel?: string;
  skillCleaning?: boolean;
  skillWashing?: boolean;
  skillCooking?: boolean;
  skillIroning?: boolean;
  skillSewing?: boolean;
  skillBabysitting?: boolean;
  skillChildCare?: boolean;
  countryOfTravel?: string;
  officeName?: string;
  partnerAgencyId?: string | null;
  contractDate?: string;
  officeId: string;
  photoPath?: string;
  fullPhotoPath?: string;
  visaNumber?: string;
  visaType?: string;
  sponsorName?: string;
  sponsorIdNumber?: string;
  sponsorPhone?: string;
  sponsorAddress?: string;
  sponsorArabicName?: string;
  agentName?: string;
  applicationNo?: string;
  fileNo?: string;
  wakalaNo?: string;
  contractNo?: string;
  stickerVisaNo?: string;
  signedOn?: string;
  relativeName?: string;
  relativePhone?: string;
  relativeKinship?: string;
  relativeGender?: string;
  relativeBirthDate?: string;
  relativeCity?: string;
  relativeRegion?: string;
  relativeSubcity?: string;
  relativeWoreda?: string;
  relativeHouseNo?: string;
  contactPerson2?: string;
  contactPhone2?: string;
  cocCenterName?: string;
  certificateNo?: string;
  certifiedDate?: string;
  medicalPlace?: string;
  status: number;
  currentStageId?: string;
  currentStageName?: string;
  currentStatusValues?: Record<string, string>;
  visibleInStages?: string[];
  registeredAt: string;
  registeredBy?: string;
  fullName: string;
}

export interface CandidateListDto {
  id: string;
  fullName: string;
  passportNumber: string;
  labourId?: string;
  currentStageName?: string;
  currentStatusValues?: Record<string, string>;
  countryOfTravel?: string;
  officeName?: string;
  status: string;
  registeredAt: string;
  dateOfBirth?: string;
  age?: number;
  occupation?: string;
  sponsorName?: string;
  sponsorIdNumber?: string;
  visaNumber?: string;
  agentName?: string;
  worksIn?: string;
}

export interface CandidateDocument {
  id: string;
  candidateId: string;
  fileName: string;
  originalFileName: string;
  contentType: string;
  filePath: string;
  thumbnailPath?: string;
  documentType: number;
  fileSizeBytes: number;
  uploadedAt: string;
  uploadedBy?: string;
}

export interface TimelineEntry {
  id: string;
  eventType: number;
  fromStageName?: string;
  toStageName?: string;
  userName: string;
  timestamp: string;
  notes?: string;
}
