// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimbaFlow.Infrastructure.Persistence;

#nullable disable

namespace SimbaFlow.Infrastructure.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260721133610_AddCandidateStageEnteredAt")]
    partial class AddCandidateStageEnteredAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Candidates.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateOnly?>("ContractDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_date");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("CountryOfTravel")
                        .HasColumnType("text")
                        .HasColumnName("country_of_travel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_stage_id");

                    b.Property<string>("CurrentStageName")
                        .HasColumnType("text")
                        .HasColumnName("current_stage_name");

                    b.Property<string>("CurrentStatusValues")
                        .HasColumnType("text")
                        .HasColumnName("current_status_values");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LabourId")
                        .HasColumnType("text")
                        .HasColumnName("labour_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Nationality")
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uuid")
                        .HasColumnName("office_id");

                    b.Property<string>("OfficeName")
                        .HasColumnType("text")
                        .HasColumnName("office_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passport_number");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text")
                        .HasColumnName("photo_path");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("RegisteredBy")
                        .HasColumnType("text")
                        .HasColumnName("registered_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("StageEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stage_entered_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("VisibleInStages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visible_in_stages");

                    b.HasKey("Id")
                        .HasName("pk_candidates");

                    b.HasIndex("CurrentStageId")
                        .HasDatabaseName("ix_candidates_current_stage_id");

                    b.HasIndex("LabourId")
                        .IsUnique()
                        .HasDatabaseName("ix_candidates_labour_id")
                        .HasFilter("labour_id IS NOT NULL");

                    b.HasIndex("OfficeId")
                        .HasDatabaseName("ix_candidates_office_id");

                    b.HasIndex("PassportNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_candidates_passport_number");

                    b.HasIndex("CurrentStageId", "StageEnteredAt")
                        .HasDatabaseName("ix_candidates_current_stage_id_stage_entered_at");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Candidates.CandidateDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_path");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_candidate_documents");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_candidate_documents_candidate_id");

                    b.ToTable("candidate_documents", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_tenant_roles");

                    b.ToTable("tenant_roles", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantRolePermission", b =>
                {
                    b.Property<Guid>("TenantRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_role_id");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("text")
                        .HasColumnName("permission_code");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("text")
                        .HasColumnName("granted_by");

                    b.HasKey("TenantRoleId", "PermissionCode")
                        .HasName("pk_tenant_role_permissions");

                    b.ToTable("tenant_role_permissions", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TenantRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("text")
                        .HasColumnName("assigned_by");

                    b.HasKey("UserId", "TenantRoleId")
                        .HasName("pk_tenant_user_roles");

                    b.HasIndex("TenantRoleId")
                        .HasDatabaseName("ix_tenant_user_roles_tenant_role_id");

                    b.ToTable("tenant_user_roles", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.MirrorViewRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TargetStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_stage_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_mirror_view_rules");

                    b.HasIndex("TargetStageId")
                        .HasDatabaseName("ix_mirror_view_rules_target_stage_id");

                    b.HasIndex("WorkflowStageId")
                        .HasDatabaseName("ix_mirror_view_rules_workflow_stage_id");

                    b.ToTable("mirror_view_rules", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.ParallelTrackDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("completion_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("track_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_parallel_track_definitions");

                    b.HasIndex("WorkflowStageId")
                        .HasDatabaseName("ix_parallel_track_definitions_workflow_stage_id");

                    b.ToTable("parallel_track_definitions", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.StageMandatoryField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TransitionRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("transition_rule_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_stage_mandatory_fields");

                    b.HasIndex("TransitionRuleId")
                        .HasDatabaseName("ix_stage_mandatory_fields_transition_rule_id");

                    b.HasIndex("WorkflowStageId")
                        .HasDatabaseName("ix_stage_mandatory_fields_workflow_stage_id");

                    b.ToTable("stage_mandatory_fields", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definitions");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("FromStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_stage_id");

                    b.Property<string>("FromStageName")
                        .HasColumnType("text")
                        .HasColumnName("from_stage_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("ToStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_stage_id");

                    b.Property<string>("ToStageName")
                        .HasColumnType("text")
                        .HasColumnName("to_stage_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_workflow_events");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_workflow_events_timestamp");

                    b.HasIndex("CandidateId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_events_candidate_id_sequence_number");

                    b.ToTable("workflow_events", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage_name");

                    b.Property<string>("StatusValues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_values");

                    b.Property<string>("VisibleInStages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visible_in_stages");

                    b.HasKey("Id")
                        .HasName("pk_workflow_snapshots");

                    b.HasIndex("CandidateId", "SequenceNumber")
                        .HasDatabaseName("ix_workflow_snapshots_candidate_id_sequence_number");

                    b.ToTable("workflow_snapshots", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFinalStage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final_stage");

                    b.Property<bool>("IsInitialStage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_initial_stage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("StageType")
                        .HasColumnType("integer")
                        .HasColumnName("stage_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_stages");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_workflow_stages_workflow_definition_id");

                    b.ToTable("workflow_stages", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStageStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TrackName")
                        .HasColumnType("text")
                        .HasColumnName("track_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_stage_statuses");

                    b.HasIndex("WorkflowStageId")
                        .HasDatabaseName("ix_workflow_stage_statuses_workflow_stage_id");

                    b.ToTable("workflow_stage_statuses", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowTransitionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_roles");

                    b.Property<string>("ButtonIcon")
                        .HasColumnType("text")
                        .HasColumnName("button_icon");

                    b.Property<string>("ButtonLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("button_label");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("RemoveFromSource")
                        .HasColumnType("boolean")
                        .HasColumnName("remove_from_source");

                    b.Property<string>("RequiredFields")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_fields");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SourceStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_stage_id");

                    b.Property<Guid>("TargetStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_stage_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_transition_rules");

                    b.HasIndex("SourceStageId")
                        .HasDatabaseName("ix_workflow_transition_rules_source_stage_id");

                    b.HasIndex("TargetStageId")
                        .HasDatabaseName("ix_workflow_transition_rules_target_stage_id");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_workflow_transition_rules_workflow_definition_id");

                    b.ToTable("workflow_transition_rules", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Candidates.CandidateDocument", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Candidates.Candidate", "Candidate")
                        .WithMany("Documents")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_documents_candidates_candidate_id");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantRolePermission", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Tenancy.TenantRole", "TenantRole")
                        .WithMany("Permissions")
                        .HasForeignKey("TenantRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_role_permissions_tenant_roles_tenant_role_id");

                    b.Navigation("TenantRole");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantUserRole", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Tenancy.TenantRole", "TenantRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("TenantRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_user_roles_tenant_roles_tenant_role_id");

                    b.Navigation("TenantRole");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.MirrorViewRule", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "TargetStage")
                        .WithMany()
                        .HasForeignKey("TargetStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mirror_view_rules_workflow_stages_target_stage_id");

                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "WorkflowStage")
                        .WithMany("MirrorViewRules")
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mirror_view_rules_workflow_stages_workflow_stage_id");

                    b.Navigation("TargetStage");

                    b.Navigation("WorkflowStage");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.ParallelTrackDefinition", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "WorkflowStage")
                        .WithMany("ParallelTracks")
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parallel_track_definitions_workflow_stages_workflow_stage_id");

                    b.Navigation("WorkflowStage");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.StageMandatoryField", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowTransitionRule", "TransitionRule")
                        .WithMany()
                        .HasForeignKey("TransitionRuleId")
                        .HasConstraintName("fk_stage_mandatory_fields_workflow_transition_rules_transition");

                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "WorkflowStage")
                        .WithMany("MandatoryFields")
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_mandatory_fields_workflow_stages_workflow_stage_id");

                    b.Navigation("TransitionRule");

                    b.Navigation("WorkflowStage");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_stages_workflow_definitions_workflow_definition_id");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStageStatus", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "WorkflowStage")
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_stage_statuses_workflow_stages_workflow_stage_id");

                    b.Navigation("WorkflowStage");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowTransitionRule", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "SourceStage")
                        .WithMany()
                        .HasForeignKey("SourceStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transition_rules_workflow_stages_source_stage_id");

                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "TargetStage")
                        .WithMany()
                        .HasForeignKey("TargetStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transition_rules_workflow_stages_target_stage_id");

                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("TransitionRules")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transition_rules_workflow_definitions_workflow_def");

                    b.Navigation("SourceStage");

                    b.Navigation("TargetStage");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Candidates.Candidate", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowDefinition", b =>
                {
                    b.Navigation("Stages");

                    b.Navigation("TransitionRules");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", b =>
                {
                    b.Navigation("MandatoryFields");

                    b.Navigation("MirrorViewRules");

                    b.Navigation("ParallelTracks");

                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
