// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimbaFlow.Infrastructure.Persistence;

#nullable disable

namespace SimbaFlow.Infrastructure.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Candidates.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AgentName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_name");

                    b.Property<string>("ApplicationNo")
                        .HasColumnType("text")
                        .HasColumnName("application_no");

                    b.Property<string>("ArabicLevel")
                        .HasColumnType("text")
                        .HasColumnName("arabic_level");

                    b.Property<string>("BiometricId")
                        .HasColumnType("text")
                        .HasColumnName("biometric_id");

                    b.Property<string>("CertificateNo")
                        .HasColumnType("text")
                        .HasColumnName("certificate_no");

                    b.Property<DateOnly?>("CertifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("certified_date");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CocCenterName")
                        .HasColumnType("text")
                        .HasColumnName("coc_center_name");

                    b.Property<string>("ContactPerson2")
                        .HasColumnType("text")
                        .HasColumnName("contact_person2");

                    b.Property<string>("ContactPhone2")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone2");

                    b.Property<DateOnly?>("ContractDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_date");

                    b.Property<string>("ContractNo")
                        .HasColumnType("text")
                        .HasColumnName("contract_no");

                    b.Property<string>("ContractPeriod")
                        .HasColumnType("text")
                        .HasColumnName("contract_period");

                    b.Property<string>("CookingLevel")
                        .HasColumnType("text")
                        .HasColumnName("cooking_level");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("CountryOfTravel")
                        .HasColumnType("text")
                        .HasColumnName("country_of_travel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_stage_id");

                    b.Property<string>("CurrentStageName")
                        .HasColumnType("text")
                        .HasColumnName("current_stage_name");

                    b.Property<string>("CurrentStatusValues")
                        .HasColumnType("text")
                        .HasColumnName("current_status_values");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EnglishLevel")
                        .HasColumnType("text")
                        .HasColumnName("english_level");

                    b.Property<int?>("ExperienceAbroadYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_abroad_years");

                    b.Property<string>("FileNo")
                        .HasColumnType("text")
                        .HasColumnName("file_no");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FullPhotoPath")
                        .HasColumnType("text")
                        .HasColumnName("full_photo_path");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Height")
                        .HasColumnType("text")
                        .HasColumnName("height");

                    b.Property<string>("HouseNo")
                        .HasColumnType("text")
                        .HasColumnName("house_no");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LabourId")
                        .HasColumnType("text")
                        .HasColumnName("labour_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LocalFullName")
                        .HasColumnType("text")
                        .HasColumnName("local_full_name");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text")
                        .HasColumnName("marital_status");

                    b.Property<string>("MedicalPlace")
                        .HasColumnType("text")
                        .HasColumnName("medical_place");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("MonthlySalary")
                        .HasColumnType("text")
                        .HasColumnName("monthly_salary");

                    b.Property<string>("NationalId")
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("Nationality")
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<int?>("NumberOfChildren")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_children");

                    b.Property<string>("Occupation")
                        .HasColumnType("text")
                        .HasColumnName("occupation");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uuid")
                        .HasColumnName("office_id");

                    b.Property<string>("OfficeName")
                        .HasColumnType("text")
                        .HasColumnName("office_name");

                    b.Property<string>("OtherLanguages")
                        .HasColumnType("text")
                        .HasColumnName("other_languages");

                    b.Property<Guid?>("PartnerAgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_agency_id");

                    b.Property<DateOnly?>("PassportExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("passport_expiry_date");

                    b.Property<DateOnly?>("PassportIssueDate")
                        .HasColumnType("date")
                        .HasColumnName("passport_issue_date");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passport_number");

                    b.Property<string>("PassportPlaceOfIssue")
                        .HasColumnType("text")
                        .HasColumnName("passport_place_of_issue");

                    b.Property<string>("PassportType")
                        .HasColumnType("text")
                        .HasColumnName("passport_type");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text")
                        .HasColumnName("photo_path");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("Qualification")
                        .HasColumnType("text")
                        .HasColumnName("qualification");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text")
                        .HasColumnName("reference_no");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("RegisteredBy")
                        .HasColumnType("text")
                        .HasColumnName("registered_by");

                    b.Property<DateOnly?>("RelativeBirthDate")
                        .HasColumnType("date")
                        .HasColumnName("relative_birth_date");

                    b.Property<string>("RelativeCity")
                        .HasColumnType("text")
                        .HasColumnName("relative_city");

                    b.Property<string>("RelativeGender")
                        .HasColumnType("text")
                        .HasColumnName("relative_gender");

                    b.Property<string>("RelativeHouseNo")
                        .HasColumnType("text")
                        .HasColumnName("relative_house_no");

                    b.Property<string>("RelativeKinship")
                        .HasColumnType("text")
                        .HasColumnName("relative_kinship");

                    b.Property<string>("RelativeName")
                        .HasColumnType("text")
                        .HasColumnName("relative_name");

                    b.Property<string>("RelativePhone")
                        .HasColumnType("text")
                        .HasColumnName("relative_phone");

                    b.Property<string>("RelativeRegion")
                        .HasColumnType("text")
                        .HasColumnName("relative_region");

                    b.Property<string>("RelativeSubcity")
                        .HasColumnType("text")
                        .HasColumnName("relative_subcity");

                    b.Property<string>("RelativeWoreda")
                        .HasColumnType("text")
                        .HasColumnName("relative_woreda");

                    b.Property<string>("Religion")
                        .HasColumnType("text")
                        .HasColumnName("religion");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly?>("SignedOn")
                        .HasColumnType("date")
                        .HasColumnName("signed_on");

                    b.Property<bool>("SkillBabysitting")
                        .HasColumnType("boolean")
                        .HasColumnName("skill_babysitting");

                    b.Property<bool>("SkillChildCare")
                        .HasColumnType("boolean")
                        .HasColumnName("skill_child_care");

                    b.Property<bool>("SkillCleaning")
                        .HasColumnType("boolean")
                        .HasColumnName("skill_cleaning");

                    b.Property<bool>("SkillCooking")
                        .HasColumnType("boolean")
                        .HasColumnName("skill_cooking");

                    b.Property<bool>("SkillIroning")
                        .HasColumnType("boolean")
                        .HasColumnName("skill_ironing");

                    b.Property<bool>("SkillSewing")
                        .HasColumnType("boolean")
                        .HasColumnName("skill_sewing");

                    b.Property<bool>("SkillWashing")
                        .HasColumnType("boolean")
                        .HasColumnName("skill_washing");

                    b.Property<string>("SponsorAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sponsor_address");

                    b.Property<string>("SponsorArabicName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sponsor_arabic_name");

                    b.Property<string>("SponsorIdNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sponsor_id_number");

                    b.Property<string>("SponsorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sponsor_name");

                    b.Property<string>("SponsorPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sponsor_phone");

                    b.Property<DateTime?>("StageEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stage_entered_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StickerVisaNo")
                        .HasColumnType("text")
                        .HasColumnName("sticker_visa_no");

                    b.Property<string>("Subcity")
                        .HasColumnType("text")
                        .HasColumnName("subcity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("VisaNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("visa_number");

                    b.Property<string>("VisaType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("visa_type");

                    b.Property<string>("VisibleInStages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visible_in_stages");

                    b.Property<string>("WakalaNo")
                        .HasColumnType("text")
                        .HasColumnName("wakala_no");

                    b.Property<string>("Weight")
                        .HasColumnType("text")
                        .HasColumnName("weight");

                    b.Property<string>("Woreda")
                        .HasColumnType("text")
                        .HasColumnName("woreda");

                    b.Property<string>("WorksIn")
                        .HasColumnType("text")
                        .HasColumnName("works_in");

                    b.HasKey("Id")
                        .HasName("pk_candidates");

                    b.HasIndex("CurrentStageId")
                        .HasDatabaseName("ix_candidates_current_stage_id");

                    b.HasIndex("LabourId")
                        .IsUnique()
                        .HasDatabaseName("ix_candidates_labour_id")
                        .HasFilter("labour_id IS NOT NULL");

                    b.HasIndex("OfficeId")
                        .HasDatabaseName("ix_candidates_office_id");

                    b.HasIndex("PassportNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_candidates_passport_number");

                    b.HasIndex("CurrentStageId", "StageEnteredAt")
                        .HasDatabaseName("ix_candidates_current_stage_id_stage_entered_at");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Candidates.CandidateDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_path");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_candidate_documents");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_candidate_documents_candidate_id");

                    b.ToTable("candidate_documents", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_code")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BalanceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance_amount");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateOnly?>("ContractDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_date");

                    b.Property<string>("CountryOfTravel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("country_of_travel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OfficeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("office_name");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalFeesAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_fees_amount");

                    b.Property<decimal>("TotalPaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_paid_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_commissions");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_commissions_candidate_id")
                        .HasFilter("is_deleted = FALSE");

                    b.HasIndex("OpenedAt")
                        .HasDatabaseName("ix_commissions_opened_at")
                        .HasFilter("is_deleted = FALSE");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_commissions_status")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("commissions", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.CommissionFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountEtb")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_etb");

                    b.Property<Guid>("CommissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<int>("FeeType")
                        .HasColumnType("integer")
                        .HasColumnName("fee_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_commission_fees");

                    b.HasIndex("CommissionId")
                        .HasDatabaseName("ix_commission_fees_commission_id")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("commission_fees", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_disputes");

                    b.HasIndex("CommissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_disputes_commission_id")
                        .HasFilter("is_deleted = FALSE AND status = 0");

                    b.ToTable("disputes", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.FinanceCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("NextJournalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_journal_number");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_finance_counters");

                    b.ToTable("finance_counters", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("EntryNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entry_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by_user_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("EntryNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_entry_number")
                        .HasFilter("is_deleted = FALSE");

                    b.HasIndex("SourceType", "SourceId")
                        .HasDatabaseName("ix_journal_entries_source_type_source_id");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<string>("Memo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("memo");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_journal_lines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journal_lines_account_id");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_journal_lines_journal_entry_id");

                    b.ToTable("journal_lines", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountEtb")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_etb");

                    b.Property<Guid>("CommissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<decimal>("ExchangeRateToEtb")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("exchange_rate_to_etb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reference");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CommissionId")
                        .HasDatabaseName("ix_payments_commission_id")
                        .HasFilter("is_deleted = FALSE");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_payments_journal_entry_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_tenant_roles");

                    b.ToTable("tenant_roles", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantRolePermission", b =>
                {
                    b.Property<Guid>("TenantRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_role_id");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("text")
                        .HasColumnName("permission_code");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("text")
                        .HasColumnName("granted_by");

                    b.HasKey("TenantRoleId", "PermissionCode")
                        .HasName("pk_tenant_role_permissions");

                    b.ToTable("tenant_role_permissions", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TenantRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("text")
                        .HasColumnName("assigned_by");

                    b.HasKey("UserId", "TenantRoleId")
                        .HasName("pk_tenant_user_roles");

                    b.HasIndex("TenantRoleId")
                        .HasDatabaseName("ix_tenant_user_roles_tenant_role_id");

                    b.ToTable("tenant_user_roles", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Travel.ExceptionCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("FinancialImpactAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("financial_impact_amount");

                    b.Property<string>("FinancialImpactCurrency")
                        .HasColumnType("text")
                        .HasColumnName("financial_impact_currency");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<string>("ResolutionSummary")
                        .HasColumnType("text")
                        .HasColumnName("resolution_summary");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_exception_cases");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_exception_cases_candidate_id")
                        .HasFilter("is_deleted = FALSE AND status = 0");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_exception_cases_status");

                    b.ToTable("exception_cases", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Travel.InvestigationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentDocumentIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attachment_document_ids");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ExceptionCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exception_case_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_investigation_notes");

                    b.HasIndex("ExceptionCaseId")
                        .HasDatabaseName("ix_investigation_notes_exception_case_id");

                    b.ToTable("investigation_notes", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Travel.LiabilityAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<Guid>("ExceptionCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exception_case_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Party")
                        .HasColumnType("integer")
                        .HasColumnName("party");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_liability_assignments");

                    b.HasIndex("ExceptionCaseId")
                        .HasDatabaseName("ix_liability_assignments_exception_case_id");

                    b.ToTable("liability_assignments", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.MirrorViewRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TargetStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_stage_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_mirror_view_rules");

                    b.HasIndex("TargetStageId")
                        .HasDatabaseName("ix_mirror_view_rules_target_stage_id");

                    b.HasIndex("WorkflowStageId")
                        .HasDatabaseName("ix_mirror_view_rules_workflow_stage_id");

                    b.ToTable("mirror_view_rules", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.ParallelTrackDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("completion_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("track_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_parallel_track_definitions");

                    b.HasIndex("WorkflowStageId")
                        .HasDatabaseName("ix_parallel_track_definitions_workflow_stage_id");

                    b.ToTable("parallel_track_definitions", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.StageMandatoryField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TransitionRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("transition_rule_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_stage_mandatory_fields");

                    b.HasIndex("TransitionRuleId")
                        .HasDatabaseName("ix_stage_mandatory_fields_transition_rule_id");

                    b.HasIndex("WorkflowStageId")
                        .HasDatabaseName("ix_stage_mandatory_fields_workflow_stage_id");

                    b.ToTable("stage_mandatory_fields", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definitions");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("FromStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_stage_id");

                    b.Property<string>("FromStageName")
                        .HasColumnType("text")
                        .HasColumnName("from_stage_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("ToStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_stage_id");

                    b.Property<string>("ToStageName")
                        .HasColumnType("text")
                        .HasColumnName("to_stage_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_workflow_events");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_workflow_events_timestamp");

                    b.HasIndex("CandidateId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_events_candidate_id_sequence_number");

                    b.ToTable("workflow_events", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage_name");

                    b.Property<string>("StatusValues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_values");

                    b.Property<string>("VisibleInStages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visible_in_stages");

                    b.HasKey("Id")
                        .HasName("pk_workflow_snapshots");

                    b.HasIndex("CandidateId", "SequenceNumber")
                        .HasDatabaseName("ix_workflow_snapshots_candidate_id_sequence_number");

                    b.ToTable("workflow_snapshots", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFinalStage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final_stage");

                    b.Property<bool>("IsInitialStage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_initial_stage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("StageType")
                        .HasColumnType("integer")
                        .HasColumnName("stage_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_stages");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_workflow_stages_workflow_definition_id");

                    b.ToTable("workflow_stages", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStageStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TrackName")
                        .HasColumnType("text")
                        .HasColumnName("track_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_stage_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_stage_statuses");

                    b.HasIndex("WorkflowStageId")
                        .HasDatabaseName("ix_workflow_stage_statuses_workflow_stage_id");

                    b.ToTable("workflow_stage_statuses", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowTransitionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_roles");

                    b.Property<string>("ButtonIcon")
                        .HasColumnType("text")
                        .HasColumnName("button_icon");

                    b.Property<string>("ButtonLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("button_label");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("RemoveFromSource")
                        .HasColumnType("boolean")
                        .HasColumnName("remove_from_source");

                    b.Property<string>("RequiredFields")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_fields");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SourceStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_stage_id");

                    b.Property<Guid>("TargetStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_stage_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_transition_rules");

                    b.HasIndex("SourceStageId")
                        .HasDatabaseName("ix_workflow_transition_rules_source_stage_id");

                    b.HasIndex("TargetStageId")
                        .HasDatabaseName("ix_workflow_transition_rules_target_stage_id");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_workflow_transition_rules_workflow_definition_id");

                    b.ToTable("workflow_transition_rules", (string)null);
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Candidates.CandidateDocument", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Candidates.Candidate", "Candidate")
                        .WithMany("Documents")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_documents_candidates_candidate_id");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.CommissionFee", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Finance.Commission", "Commission")
                        .WithMany("Fees")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commission_fees_commissions_commission_id");

                    b.Navigation("Commission");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.Dispute", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Finance.Commission", "Commission")
                        .WithMany("Disputes")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disputes_commissions_commission_id");

                    b.Navigation("Commission");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.JournalLine", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Finance.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_accounts_account_id");

                    b.HasOne("SimbaFlow.Domain.Entities.Finance.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_journal_entries_journal_entry_id");

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.Payment", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Finance.Commission", "Commission")
                        .WithMany("Payments")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_commissions_commission_id");

                    b.HasOne("SimbaFlow.Domain.Entities.Finance.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_journal_entries_journal_entry_id");

                    b.Navigation("Commission");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantRolePermission", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Tenancy.TenantRole", "TenantRole")
                        .WithMany("Permissions")
                        .HasForeignKey("TenantRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_role_permissions_tenant_roles_tenant_role_id");

                    b.Navigation("TenantRole");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantUserRole", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Tenancy.TenantRole", "TenantRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("TenantRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_user_roles_tenant_roles_tenant_role_id");

                    b.Navigation("TenantRole");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Travel.InvestigationNote", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Travel.ExceptionCase", "ExceptionCase")
                        .WithMany("Notes")
                        .HasForeignKey("ExceptionCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investigation_notes_exception_cases_exception_case_id");

                    b.Navigation("ExceptionCase");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Travel.LiabilityAssignment", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Travel.ExceptionCase", "ExceptionCase")
                        .WithMany("Liabilities")
                        .HasForeignKey("ExceptionCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_liability_assignments_exception_cases_exception_case_id");

                    b.Navigation("ExceptionCase");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.MirrorViewRule", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "TargetStage")
                        .WithMany()
                        .HasForeignKey("TargetStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mirror_view_rules_workflow_stages_target_stage_id");

                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "WorkflowStage")
                        .WithMany("MirrorViewRules")
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mirror_view_rules_workflow_stages_workflow_stage_id");

                    b.Navigation("TargetStage");

                    b.Navigation("WorkflowStage");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.ParallelTrackDefinition", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "WorkflowStage")
                        .WithMany("ParallelTracks")
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parallel_track_definitions_workflow_stages_workflow_stage_id");

                    b.Navigation("WorkflowStage");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.StageMandatoryField", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowTransitionRule", "TransitionRule")
                        .WithMany()
                        .HasForeignKey("TransitionRuleId")
                        .HasConstraintName("fk_stage_mandatory_fields_workflow_transition_rules_transition");

                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "WorkflowStage")
                        .WithMany("MandatoryFields")
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_mandatory_fields_workflow_stages_workflow_stage_id");

                    b.Navigation("TransitionRule");

                    b.Navigation("WorkflowStage");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_stages_workflow_definitions_workflow_definition_id");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStageStatus", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "WorkflowStage")
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_stage_statuses_workflow_stages_workflow_stage_id");

                    b.Navigation("WorkflowStage");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowTransitionRule", b =>
                {
                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "SourceStage")
                        .WithMany()
                        .HasForeignKey("SourceStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transition_rules_workflow_stages_source_stage_id");

                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", "TargetStage")
                        .WithMany()
                        .HasForeignKey("TargetStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transition_rules_workflow_stages_target_stage_id");

                    b.HasOne("SimbaFlow.Domain.Entities.Workflow.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("TransitionRules")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transition_rules_workflow_definitions_workflow_def");

                    b.Navigation("SourceStage");

                    b.Navigation("TargetStage");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Candidates.Candidate", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.Commission", b =>
                {
                    b.Navigation("Disputes");

                    b.Navigation("Fees");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Finance.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Tenancy.TenantRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Travel.ExceptionCase", b =>
                {
                    b.Navigation("Liabilities");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowDefinition", b =>
                {
                    b.Navigation("Stages");

                    b.Navigation("TransitionRules");
                });

            modelBuilder.Entity("SimbaFlow.Domain.Entities.Workflow.WorkflowStage", b =>
                {
                    b.Navigation("MandatoryFields");

                    b.Navigation("MirrorViewRules");

                    b.Navigation("ParallelTracks");

                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
