using SimbaFlow.Domain.Common;
using SimbaFlow.Domain.Entities.Identity;
using SimbaFlow.Domain.Enums;

namespace SimbaFlow.Domain.Entities.Staff;

/// <summary>
/// The clinical/resource identity of a person in the organization.
/// Analogous to Epic's "SER" (Provider/Schedulable Resource).
/// 
/// A StaffProfile may or may not be linked to a User account:
/// - External partners may have a StaffProfile but no login.
/// - IT support staff have a login (ApplicationUser) but no StaffProfile.
/// </summary>
public class StaffProfile : BaseEntity
{
    // ──── Link to Security Context ────
    // Nullable: support staff may not have accounts; external providers never do.
    public Guid? UserId { get; set; }
    public ApplicationUser? User { get; set; }

    // ──── Core Identity ────
    /// <summary>Internal staff ID (e.g., "STF-00123"). Generated by HR.</summary>
    public string StaffId { get; set; } = string.Empty;

    /// <summary>Legal first name. Must match government ID for credentialing.</summary>
    public string FirstName { get; set; } = string.Empty;

    public string LastName { get; set; } = string.Empty;
    public string? MiddleName { get; set; }

    /// <summary>Preferred name for communication and badges.</summary>
    public string? PreferredName { get; set; }

    public string? Email { get; set; }
    public string? PhoneNumber { get; set; }
    public DateOnly? DateOfBirth { get; set; }

    // ──── Professional Classification ────
    public StaffType StaffType { get; set; }

    /// <summary>Clinical title (e.g., "MD", "DO", "RN", "FNP"). Distinct from org title.</summary>
    public string? ClinicalTitle { get; set; }

    /// <summary>Organizational title (e.g., "Department Head", "Senior Consultant").</summary>
    public string? Title { get; set; }

    public string? Specialization { get; set; }

    // ──── Employment Lifecycle ────
    public EmploymentStatus EmploymentStatus { get; set; } = EmploymentStatus.Active;
    public DateOnly? HireDate { get; set; }
    public DateOnly? TerminationDate { get; set; }

    /// <summary>
    /// True for residents or trainees — all clinical notes require attending physician co-signature.
    /// </summary>
    public bool RequiresCoSignature { get; set; }

    public bool IsActive { get; set; } = true;

    // ──── Legacy (to be migrated to StaffDepartmentAffiliation) ────
    /// <summary>
    /// Deprecated: Use StaffDepartmentAffiliations for proper temporal department tracking.
    /// Retained temporarily for backward compatibility during migration.
    /// </summary>
    [Obsolete("Use DepartmentAffiliations collection instead. Will be removed after migration.")]
    public string? Department { get; set; }

    /// <summary>
    /// Deprecated: Use StaffIdentifiers collection for proper identifier tracking.
    /// Retained temporarily for backward compatibility during migration.
    /// </summary>
    [Obsolete("Use Identifiers collection instead. Will be removed after migration.")]
    public string? LicenseNumber { get; set; }

    // ──── Navigation Properties ────
    public ICollection<StaffIdentifier> Identifiers { get; set; } = [];
    public ICollection<StaffDepartmentAffiliation> DepartmentAffiliations { get; set; } = [];
}
