-- Apply tables to all tenant schemas

CREATE TABLE IF NOT EXISTS tenant_ethio_star.candidates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, middle_name VARCHAR(100), passport_number VARCHAR(20) NOT NULL UNIQUE, labour_id VARCHAR(50), date_of_birth DATE NOT NULL, gender SMALLINT NOT NULL DEFAULT 0, nationality VARCHAR(100), phone_number VARCHAR(20), email VARCHAR(200), address VARCHAR(500), city VARCHAR(100), country VARCHAR(100), country_of_travel VARCHAR(100), office_name VARCHAR(200), contract_date DATE, office_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000', photo_path VARCHAR(500), status SMALLINT NOT NULL DEFAULT 0, current_stage_id UUID, current_stage_name VARCHAR(100), current_status_values TEXT DEFAULT '{}', visible_in_stages TEXT DEFAULT '[]', registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), registered_by VARCHAR(200), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by VARCHAR(200), updated_at TIMESTAMPTZ, updated_by VARCHAR(200), is_deleted BOOLEAN NOT NULL DEFAULT FALSE, row_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tenant_ethio_star.tenant_roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) NOT NULL, code VARCHAR(100) NOT NULL, description TEXT, is_system_role BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by VARCHAR(200), updated_at TIMESTAMPTZ, updated_by VARCHAR(200), is_deleted BOOLEAN NOT NULL DEFAULT FALSE, row_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tenant_ethio_star.tenant_role_permissions (tenant_role_id UUID NOT NULL, permission_code VARCHAR(100) NOT NULL, granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), granted_by VARCHAR(200), PRIMARY KEY (tenant_role_id, permission_code));
CREATE TABLE IF NOT EXISTS tenant_ethio_star.tenant_user_roles (user_id UUID NOT NULL, tenant_role_id UUID NOT NULL, assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), assigned_by VARCHAR(200), PRIMARY KEY (user_id, tenant_role_id));

CREATE TABLE IF NOT EXISTS tenant_addis_manpower.candidates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, middle_name VARCHAR(100), passport_number VARCHAR(20) NOT NULL UNIQUE, labour_id VARCHAR(50), date_of_birth DATE NOT NULL, gender SMALLINT NOT NULL DEFAULT 0, nationality VARCHAR(100), phone_number VARCHAR(20), email VARCHAR(200), address VARCHAR(500), city VARCHAR(100), country VARCHAR(100), country_of_travel VARCHAR(100), office_name VARCHAR(200), contract_date DATE, office_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000', photo_path VARCHAR(500), status SMALLINT NOT NULL DEFAULT 0, current_stage_id UUID, current_stage_name VARCHAR(100), current_status_values TEXT DEFAULT '{}', visible_in_stages TEXT DEFAULT '[]', registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), registered_by VARCHAR(200), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by VARCHAR(200), updated_at TIMESTAMPTZ, updated_by VARCHAR(200), is_deleted BOOLEAN NOT NULL DEFAULT FALSE, row_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tenant_addis_manpower.tenant_roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) NOT NULL, code VARCHAR(100) NOT NULL, description TEXT, is_system_role BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by VARCHAR(200), updated_at TIMESTAMPTZ, updated_by VARCHAR(200), is_deleted BOOLEAN NOT NULL DEFAULT FALSE, row_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tenant_addis_manpower.tenant_role_permissions (tenant_role_id UUID NOT NULL, permission_code VARCHAR(100) NOT NULL, granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), granted_by VARCHAR(200), PRIMARY KEY (tenant_role_id, permission_code));
CREATE TABLE IF NOT EXISTS tenant_addis_manpower.tenant_user_roles (user_id UUID NOT NULL, tenant_role_id UUID NOT NULL, assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), assigned_by VARCHAR(200), PRIMARY KEY (user_id, tenant_role_id));

CREATE TABLE IF NOT EXISTS tenant_golden_gate.candidates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, middle_name VARCHAR(100), passport_number VARCHAR(20) NOT NULL UNIQUE, labour_id VARCHAR(50), date_of_birth DATE NOT NULL, gender SMALLINT NOT NULL DEFAULT 0, nationality VARCHAR(100), phone_number VARCHAR(20), email VARCHAR(200), address VARCHAR(500), city VARCHAR(100), country VARCHAR(100), country_of_travel VARCHAR(100), office_name VARCHAR(200), contract_date DATE, office_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000', photo_path VARCHAR(500), status SMALLINT NOT NULL DEFAULT 0, current_stage_id UUID, current_stage_name VARCHAR(100), current_status_values TEXT DEFAULT '{}', visible_in_stages TEXT DEFAULT '[]', registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), registered_by VARCHAR(200), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by VARCHAR(200), updated_at TIMESTAMPTZ, updated_by VARCHAR(200), is_deleted BOOLEAN NOT NULL DEFAULT FALSE, row_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tenant_golden_gate.tenant_roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) NOT NULL, code VARCHAR(100) NOT NULL, description TEXT, is_system_role BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by VARCHAR(200), updated_at TIMESTAMPTZ, updated_by VARCHAR(200), is_deleted BOOLEAN NOT NULL DEFAULT FALSE, row_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tenant_golden_gate.tenant_role_permissions (tenant_role_id UUID NOT NULL, permission_code VARCHAR(100) NOT NULL, granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), granted_by VARCHAR(200), PRIMARY KEY (tenant_role_id, permission_code));
CREATE TABLE IF NOT EXISTS tenant_golden_gate.tenant_user_roles (user_id UUID NOT NULL, tenant_role_id UUID NOT NULL, assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), assigned_by VARCHAR(200), PRIMARY KEY (user_id, tenant_role_id));

CREATE TABLE IF NOT EXISTS tenant_default_agency.candidates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, middle_name VARCHAR(100), passport_number VARCHAR(20) NOT NULL UNIQUE, labour_id VARCHAR(50), date_of_birth DATE NOT NULL, gender SMALLINT NOT NULL DEFAULT 0, nationality VARCHAR(100), phone_number VARCHAR(20), email VARCHAR(200), address VARCHAR(500), city VARCHAR(100), country VARCHAR(100), country_of_travel VARCHAR(100), office_name VARCHAR(200), contract_date DATE, office_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000', photo_path VARCHAR(500), status SMALLINT NOT NULL DEFAULT 0, current_stage_id UUID, current_stage_name VARCHAR(100), current_status_values TEXT DEFAULT '{}', visible_in_stages TEXT DEFAULT '[]', registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), registered_by VARCHAR(200), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by VARCHAR(200), updated_at TIMESTAMPTZ, updated_by VARCHAR(200), is_deleted BOOLEAN NOT NULL DEFAULT FALSE, row_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tenant_default_agency.tenant_roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) NOT NULL, code VARCHAR(100) NOT NULL, description TEXT, is_system_role BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by VARCHAR(200), updated_at TIMESTAMPTZ, updated_by VARCHAR(200), is_deleted BOOLEAN NOT NULL DEFAULT FALSE, row_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tenant_default_agency.tenant_role_permissions (tenant_role_id UUID NOT NULL, permission_code VARCHAR(100) NOT NULL, granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), granted_by VARCHAR(200), PRIMARY KEY (tenant_role_id, permission_code));
CREATE TABLE IF NOT EXISTS tenant_default_agency.tenant_user_roles (user_id UUID NOT NULL, tenant_role_id UUID NOT NULL, assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), assigned_by VARCHAR(200), PRIMARY KEY (user_id, tenant_role_id));
